### ISSUE TITLE
SMS Magic Link

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#12]
We want users to be able to log in with their phone number -- upon login, they will receive a text, clicking the link will:
1. if on computer, send socket success message and log computer in (show success message on phone)
2. if on phone, log in from link

**Comment by dmitrizagidulin** [comment]
Assigning @green9016 to start on this.

**Comment by dmitrizagidulin** [comment]
@green9016 Update to direction - we'll be using AWS SMS service, instead of Twilio. Will get you credentials shortly.

**Comment by shawticus** [comment]
@green9016 following up, do you have credentials? Is this ready? Can I close?

**Comment by green9016** [comment]
@shawticus 
Yes, this was done.
AWS SNS credentials is in this document.
https://docs.google.com/document/d/1LwKBZZRUBmwOBplOdjQeXkVBnQVVcxMBySrnBWN8C2o/edit
