### ISSUE TITLE
Back button not going to right place

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-client#128]
To reproduce:
Go to https://dev.kaixr.world/explore
Click on a video. Hit play, click the Back button.

Expected: Have the screen change back to https://dev.kaixr.world/explore.

Actual: Screen goes back to `/` (https://dev.kaixr.world/).

I suspect we need to pass into the video player the source page (from where the user entered), and wire up the Back button to that.

**Comment by mohrtw** [comment]
Solved by #130
