### ISSUE TITLE
Email Magic Link To Login

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#13]
We want to present the user with the option to login with email. Upon login, they will receive an email with a link, and will be logged in for the duration of the session with that link. A good example at http://magicleap.com
@green9016 if this is complete, please add documentation to the readme.md on how to test, or send to @shawticus to review and add.

**Comment by dmitrizagidulin** [comment]
Implemented in #33 and https://github.com/xrchat/xrchat-server/pull/34, closing.
