### ISSUE TITLE
Redux state manager holds user token, etc after login

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#17]
@green9016 Please explain how the Redux store can be accessed. Can we write a manager class for getting and setting the store and document the API for the other developers?

**Comment by green9016** [comment]
Hello @shawticus

**Comment by green9016** [comment]
@shawticus 
Redux document  have been written.
Please have a look this
https://github.com/xrchat/xrchat-client/blob/redux/README.md

**Comment by dmitrizagidulin** [comment]
Closing this one (there's a link to this issue in #32, for reference).
