### ISSUE TITLE
Make gallery pagination scroll arrow bigger

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-client#270]
In the video gallery view (`/explore`), the pagination scrolling arrow to the right of the videos is very small (it's about 1/4 of the video gallery rows in height).

Let's make it much bigger. (Especially on mobile, it's almost too small to click on.) It would be ideal if we had it the same height as the height of the video gallery (all 3 rows).

**Comment by mohrtw** [comment]
#277
