### ISSUE TITLE
Display error messages on Signup or Sign In.

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-client#31]
Need to display error messages to the user, when signing in or creating a new account.

To reproduce (Sign in):
Load client in browser. Click on Login link. Fill out email & password with a non-existing account, click Sign in.

Expected behavior: To see an error message "User not found." or at least "Invalid login."

Actual behavior: No error message. (Error is logged to browser console.)

To reproduce (Signup/Create Account):
Load client in browser. Click on Login link. Click on Sign up link at the bottom.

Enter an email & pw that you've already registered.

Expected behavior: To see an error message "User already registered."

Actual behavior: No error message. (Error is logged to browser console, with message "userId must be unique.")

**Comment by dmitrizagidulin** [comment]
Assigning to @green9016.

**Comment by thatpassesfor** [comment]
Currently, when the user enters an invalid email to the email magic link login, it does now display the error message, so yay!   However, 1) the error is incomprehensible to users "cannot read property "toString" of undefined and 2) the error fades too quickly.  

Recommendation:  change text of error message to "invalid email" and increase or turn off fade time limit.

**Comment by thatpassesfor** [comment]
Also, when the user enters a valid email, the same error message happens.

**Comment by mrhegemon** [comment]
Why do the magic link emails say community@slickblox.com?! I can find no mention of slickblox.com in our code. Where is this coming from?

**Comment by dmitrizagidulin** [comment]
@mrhegemon It's coming from the config I think. I'm opening a separate issue for that.

**Comment by dmitrizagidulin** [comment]
Fixed by @green9016 in PRs #73 and https://github.com/xrchat/xrchat-server/pull/46. Closing.
