### ISSUE TITLE
BUG: Refresh causes black screen

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#46]
HOW TO REPRODUCE:
Go to main site. Refresh page. Site won't load.
Make new window, open site, site loads.

@dmitrizagidulin Great task to delegate to one of our new folks to get them up to speed, unless we think it's really urgent.

**Comment by dmitrizagidulin** [comment]
@shawticus I can't reproduce this bug. (Site works after reload for me). Perhaps it's been fixed?

**Comment by shawticus** [comment]
Seems to be related to local development server.
