### ISSUE TITLE
Style user logged in status in navbar (currently black font on dark background).

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-client#48]
After login, the top right of the navbar correctly displays the user's email, and a LOGOUT link.

However, it's unstyled (shows up in black font), doesn't look right against our dark landing page.
Please fix.

<img width="339" alt="Screen Shot 2020-04-15 at 1 25 12 PM" src="https://user-images.githubusercontent.com/947005/79367989-b888b400-7f1c-11ea-80af-268d4fb7ea1b.png">

**Comment by dmitrizagidulin** [comment]
Fixed by @green9016 in PR #62, closing.

**Comment by shawticus** [comment]
Handing this to @AyushiMastro to QA and fix.

**Comment by dmitrizagidulin** [comment]
Fixed now in production mode, closing.
