### ISSUE TITLE
Cardboard icon in lower right is not labeled

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/xrchat-client#70]
Let's consider labeling the Cardboard icon in the lower right because users may not know what that means.

**Comment by shawticus** [comment]
"Enter VR"

On PCs, etc, this should remove all UI and make the canvas full screen.

**Comment by shawticus** [comment]
Since we're using the standard "VR" cardboard icon that is universal standard, I don't think the solution is to add text -- this is a bigger UX / UI design + per platform programming to think about what the "more immersive" experience is on every platform.

Pushing this to beta.

**Comment by shawticus** [comment]
@Harendraqueppelin copy of the device type switching task
