### ISSUE TITLE
Login Component / Magic Link is a Modal Window

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#74]
When user clicks "login", modal window for login should pop up instead of directing user to another page/view.

We can then remove the magicLInk.tsx file and route

**Comment by shawticus** [comment]
@dmitrizagidulin can we close this?

**Comment by dmitrizagidulin** [comment]
Tested locally, now works as of PR https://github.com/xrchat/xrchat-server/pull/88. Closing.
