### ISSUE TITLE
Combine Login and Magic Link Components

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#75]
Please combine all login + magic link options into one Login component -- all configured login options that are enabled will be displayed. Magic Link and SMS will be combined into one field, if possible,

**Comment by dmitrizagidulin** [comment]
Partly implemented by PRs #80 and #105. Current QA status:

![image](https://user-images.githubusercontent.com/947005/79901361-bc657c00-83dd-11ea-9cee-9249d399f8cf.png)

**Comment by shawticus** [comment]
@green9016 Please see image above. Looks like we're not completely implemented yet?

**Comment by green9016** [comment]
@shawticus 
I told @dmitrizagidulin before.
It is because the db schema was not updated as new.
If we re-init database, then it will be solved.
And to avoid such problems, I integrated the migration system. 
I created a PR for migration system, please review that.
Thanks

**Comment by dmitrizagidulin** [comment]
Thanks @green9016.
I have reset the database on Dev. Different error now:

![Screen Shot 2020-04-24 at 9 22 24 AM](https://user-images.githubusercontent.com/947005/80217157-3596e600-860d-11ea-9264-d5bd7aa17a06.png)

**Comment by dmitrizagidulin** [comment]
Tested locally, now works as of PR https://github.com/xrchat/xrchat-server/pull/88. Closing.
