### ISSUE TITLE
Enter VR Button crashes iPhone

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#77]
Steps to reproduce:

Press VR icon in bottom right corner on iPhone:

Show "please enter cardboard" menu -- okay.

Flip on side: goes to barrel view but page freezes

**Comment by shawticus** [comment]
@mohrtw iPhone no longer crashes, but it doesn't work, either. We should hide the iPhone cardboard image, like with Hubs, or figure out a smooth way to make it work?

**Comment by dmitrizagidulin** [comment]
This has been fixed in latest dev server; tested on iPhone. This issue can be closed.
