### ISSUE TITLE
Login Component - Based on Config

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#8]
@green9016 Goal here is a flexible login component who's contents are populated by config.

**Comment by dmitrizagidulin** [comment]
Handing over to @green9016 to start on this. Details:

Display or hide login methods (social login (gh, google, fb), email magic link, username + pw) depending on config.
That is, only display the Github login icon if there's a `GITHUB_CLIENT_ID` in the config, etc.
Same with username + pw.

We want to be able to only show 'Email link' as a sole login option, based on config.

**Comment by shawticus** [comment]
@green9016 Saw this in PRs. Please verify this is done and I will close the issue.

**Comment by dmitrizagidulin** [comment]
Implemented, deployed to dev. Closing.
