### ISSUE TITLE
Fix up email template

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/xrchat-client#82]
Currently reads "Hello
Please click the below link to **sigin** in."

Expected: **sign**

In addition, received email has no logo or personalization so at very least let's add a configurable logo.  Also, instead of the entire long text of the url, let's change it to a login button or a text link.

**Comment by dmitrizagidulin** [comment]
Assigning @AyushiMastro.

**Comment by dmitrizagidulin** [comment]
Typo is fixed by PR https://github.com/xrchat/xrchat-server/pull/70.

**Comment by shawticus** [comment]
@dmitrizagidulin closing this issue, since the typo appears to be fixed
