### ISSUE TITLE
Only need checkbox for terms and conditions

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/xrchat-client#84]
Currently:  the  login dialogue has a checkbox for terms and conditions and a separate checkbox for the privacy policy.

Expected:   A single checkbox for terms and conditions, 

Ref: https://github.com/xrchat/kxr-dev/issues/20

(the privacy policy page will be linked from the terms and conditions)

**Comment by green9016** [comment]
@dmitrizagidulin @thatpassesfor 
This issue was completed

**Comment by shawticus** [comment]
@dmitrizagidulin closing this
