### ISSUE TITLE
Implement 'Video Details' page

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-client#93]
Currently: video grid -> click on video -> video plays.

Need to implement an intermediate step.
video grid -> click on video -> video details page -> click play -> video plays.

Mockup of what the detail page looks like:

![image](https://user-images.githubusercontent.com/947005/79708894-bd3bc800-828e-11ea-91b5-de4351ab30ae.png)

**Comment by mohrtw** [comment]
Solved by #149
