### ISSUE TITLE
Custom Aframe Loading Screen

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#94]
Aframe comes with a default loading screen, but it's not good and we can't control it. We'd like to replace.

1. Remove current loading screen from a-scene.

2. Add events to kick off loading screen at start, and end on scene loaded.

3. Create a React component with a loader that displays when Aframe starts to load and until Aframe is loaded.

**Comment by shawticus** [comment]
@Harendraqueppelin We have a CSS-based loader design now. Please check in before you work on this, or let's just make sure the loader component is a dummy we can replace with our existing component.

**Comment by shawticus** [comment]
@Harendraqueppelin Actually, here's a code pen for it :)
https://codepen.io/syedsimanta03/pen/yLYzXrK

**Comment by shawticus** [comment]
@syedsimanta03 If you've already made this a component, please advise where @Harendraqueppelin can find that.

**Comment by syedsimanta03** [comment]
I will make it today @shawticus

**Comment by syedsimanta03** [comment]
> @syedsimanta03 If you've already made this a component, please advise where @Harendraqueppelin can find that.

**Comment by syedsimanta03** [comment]
> @syedsimanta03 If you've already made this a component, please advise where @Harendraqueppelin can find that.

Please check loader inside components https://github.com/xrchat/xrchat-client/pull/150

**Comment by mohrtw** [comment]
Complete with #150 and #221
